version: '3.8'

services:
  init:
    build:
      context: ./init
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/app/config.json:ro
      - config-out:/shared
    environment:
      - CONFIG_PATH=/app/config.json
      - SHARED_PATH=/shared

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - init
    volumes:
      - config-out:/config:ro
      - sqlite-data:/data
    environment:
      - CONFIG_PATH=/config/config.json
      - DB_PATH=/data/appstore.db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - config-out:/config:ro
    environment:
      - CONFIG_PATH=/config/config.json
      - BACKEND_URL=http://backend:8080
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NODE_ENV=production

volumes:
  config-out:
  sqlite-data:
