version: '3.8'

services:
  init:
    build:
      context: ./init
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/app/config.json:ro
      - config-out:/shared
      - sqlite-data:/data:rw
    environment:
      - CONFIG_PATH=/app/config.json
      - SHARED_PATH=/shared
    command: >
      sh -c "cp /app/config.json /shared/config.json &&
             mkdir -p /data &&
             touch /data/appstore.db &&
             chown -R nobody:nobody /data &&
             chmod -R 777 /data"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - init
    volumes:
      - config-out:/config:ro
      - sqlite-data:/data:rw
      - image-data:/data/images:rw
    environment:
      - CONFIG_PATH=/config/config.json
      - DB_PATH=/data/appstore.db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - config-out:/config:ro
      - ./config.json:/app/public/config.json:ro
    environment:
      - CONFIG_PATH=/config/config.json
      - NODE_ENV=production
      - NODE_ENV=production

volumes:
  config-out:
  sqlite-data:
  image-data:
